### ISSUE TITLE
Discord: Send Message input box says Websocket URL not Webhook URL

### ISSUE THREAD

**Issue by AgentDave7** [SAMMISolutions/SAMMI-Official#16]
Chrizzz has been informed of this. Posting here also so that it can be closed once the change has been applied to SAMMI.

![image](https://github.com/SAMMISolutions/SAMMI-Official/assets/131742161/126707c7-f1ef-4c0f-b984-773ac747d6a0)

It should be Webhook URL.

**Comment by christinna9031** [comment]
Already fixed in my previous commit. Thanks!
