### ISSUE TITLE
Backup feature?

### ISSUE THREAD

**Issue by Archid3vtus** [SAMMISolutions/SAMMI-Official#17]
Hey!

I got back to streaming today after a long break and I noticed that SAMMI had removed the backup functionality (or I'm not being able to find it anywhere). It is essential for me to have the ability to easily backup my decks so I had to revert my SAMMI version for that.

What happened? What do I need to do to keep constant backups of my decks and be able to change between them in recent versions?

**Comment by christinna9031** [comment]
Simply copy the whole SAMMI Folder to back it up.
