### ISSUE TITLE
support for multiple broadcasts (youtube)

### ISSUE THREAD

**Issue by gemini2186** [SAMMISolutions/SAMMI-Official#19]
Hello!
I really like your product, it makes it so easy for creativity!
But I encountered one unpleasant circumstance. The fact is that I conduct several broadcasts on YouTube at once. And apparently all the commands that I configure through commands in chat (triggers) only work on the stream that was launched last
Is there any way to fix this?
I will provide any assistance if necessary!

**Comment by christinna9031** [comment]
We do not accept feature requests via Github. Please see here: https://feedback.sammi.solutions/feature-requests
