### ISSUE TITLE
Handle leak issue with SAMMI Deck

### ISSUE THREAD

**Issue by BMF54123** [SAMMISolutions/SAMMI-Official#5]
SAMMI Deck (_not_ SAMMI Core) continuously leaks handles as long as it is running. This has actually been a problem since LB2, and has caused some very bizarre problems (e.g. microphone and controller failures) after running the program for several hours.

Steps to reproduce:
- Open Task Manager and SAMMI Deck.exe
- Switch to Task Manager's Performance tab and watch the number of CPU handles continue to grow

A friend of mine also verified this issue in LB2, and recorded over 1.7 million open handles after running the stream deck for several hours, which dropped back to a more reasonable 98K after closing the app:
![image](https://user-images.githubusercontent.com/15024035/185534713-1add7851-644e-4ba7-aba3-6d280f511eab.png)

Unfortunately I am stuck running LB1 to ensure the stability of my streaming setup as it does _not_ have this issue.

**Comment by SAMMISolutions** [comment]
We do not have the ability to modify SAMMI Deck.
