### ISSUE TITLE
Hello, could you please add a USB option to connect SAMMI Deck (.apk) to SAMMI Core.

### ISSUE THREAD

**Issue by ioerjfoige0439i** [SAMMISolutions/SAMMI-Official#7]
Hello, could you please add a USB option to connect SAMMI Deck on my android phone to SAMMI Core. I am behind a firewall where the IP can't be directly used so this is how I am connecting with other touch programs. Thank you.

**Comment by christinna9031** [comment]
We do not have access to SAMMI Deck source code, so this will be only possible (probably not though) when we release our own Web Deck.

**Comment by ioerjfoige0439i** [comment]
Hi, okay not sure where to post. Are you handling LioranBoard2 anymore? Is thi something you could add to LioranBoard2? Thanks.

**Comment by SAMMISolutions** [comment]
We no longer support any Lioranboard2 development as we have rebranded to
SAMMI.
