### ISSUE TITLE
Android app can't connect

### ISSUE THREAD

**Issue by sennewood** [SAMMISolutions/SAMMI-Official#9]
- App-Version: 2.24 (via .apk)
- SAMMI: 2022.4.4
- All WLAN devices are allowed to communicate with each other.
- SAMMI Bridge is connected to SAMMI Core

The issue is that a click on "connect" in the android app shows a loading icon for <1sec and does nothing.

**Comment by SAMMISolutions** [comment]
We do not have control over the SAMMI Deck or Android Deck, we cannot fix bugs as we do not have the source code. Please wait for our official SAMMI Web Deck to come out in the future.

**Comment by sennewood** [comment]
If it doesn't works for anybody I suggest to remove the APK file: https://github.com/SAMMISolutions/SAMMI-Official/tree/main/download

**Comment by christinna9031** [comment]
Nothing has changed on our side. And it works for everyone, else we would get other bug reports. This must be something on your side.  This isn't a tech support section, please join our Discord server at https://discord.gg/dXez8Zh so we can help you troubleshoot it further.
